AddingPowerSupport_CI/Testing
pkg/errors pull request #234
Opened 2020-12-07 07:21 UTC by santosh653

Adding Power & Updating the go versions to 1.13/1.14/1.15 as lower versions are not supported.

Adding power support ppc64le with Continues Integration/testing so that code remains architecture independent.

This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

The build is successful on both arch: amd64/ppc64le, please find the Travis Link below.
https://travis-ci.com/github/santosh653/errors

Please let me know if you need any further details?

Thank You !!

2020-12-07 09:57 UTC, davecheney requested changes
Thank you for the change. I’d be happy to take a PR to test only on go 1.14 and 1.15. 

There is nothing platform specific about the errors package that would benefit from testing on power, please remove that part of the pr. Thank you

2020-12-07 10:48 UTC, santosh653 commented
@davecheney As advised by you, I have re-run the Tests with go-1.14/1.15.,
Thank You !!

2020-12-08 16:17 UTC, santosh653 commented
@davecheney Checking herewith if you have any further queries on this PR?

Thank you !!

2020-12-09 00:53 UTC, davecheney commented
> @davecheney Checking herewith if you have any further queries on this PR?
> 
> Thank you !!

Thank you. I'm waiting on you to revert the change to the architectures, please see https://github.com/pkg/errors/pull/234#pullrequestreview-545989426

2020-12-14 06:45 UTC, davecheney approved these changes

2020-12-14 06:45 UTC, merged